# Generated by Django 5.0 on 2024-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(upload_to='1')),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
