# Generated by Django 5.0 on 2024-01-09 05:57

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(upload_to='gallery/', validators=[services.models.validate_image_size])),
                ('gallery_title', models.CharField(max_length=50)),
                ('gallery_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(max_length=50),
        ),
    ]
