# Generated by Django 5.0 on 2024-01-10 10:26

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_gallery_alter_service_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_img', models.ImageField(upload_to='team/', validators=[services.models.Team_validate_image_size])),
                ('member_name', models.CharField(max_length=50)),
                ('member_title', models.CharField(max_length=50)),
                ('member_description', models.TextField()),
                ('facebook_link', models.TextField()),
                ('whatsapp_link', models.TextField()),
                ('linkedin_link', models.TextField()),
                ('instagram_link', models.TextField()),
            ],
        ),
    ]
